// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKnAo4isoSLM22hzcGWFBiqpXOcvvj3hk',
    appId: '1:237375381267:web:d91b15b7cd54f779b844e6',
    messagingSenderId: '237375381267',
    projectId: 'nvcti-f6dfe',
    authDomain: 'nvcti-f6dfe.firebaseapp.com',
    storageBucket: 'nvcti-f6dfe.firebasestorage.app',
    measurementId: 'G-TCKF1YG0Y4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD90g2Aqbg2DAo7cqTv83feBBJE4qfHopg',
    appId: '1:237375381267:android:ec731cf42c404d03b844e6',
    messagingSenderId: '237375381267',
    projectId: 'nvcti-f6dfe',
    storageBucket: 'nvcti-f6dfe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEP2b1Y87vwHoY47_INdUR0xGBXLx5c2I',
    appId: '1:237375381267:ios:aa964d8cdb81d8bab844e6',
    messagingSenderId: '237375381267',
    projectId: 'nvcti-f6dfe',
    storageBucket: 'nvcti-f6dfe.firebasestorage.app',
    iosBundleId: 'com.example.nvcti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEP2b1Y87vwHoY47_INdUR0xGBXLx5c2I',
    appId: '1:237375381267:ios:aa964d8cdb81d8bab844e6',
    messagingSenderId: '237375381267',
    projectId: 'nvcti-f6dfe',
    storageBucket: 'nvcti-f6dfe.firebasestorage.app',
    iosBundleId: 'com.example.nvcti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKnAo4isoSLM22hzcGWFBiqpXOcvvj3hk',
    appId: '1:237375381267:web:6181e2fff081b419b844e6',
    messagingSenderId: '237375381267',
    projectId: 'nvcti-f6dfe',
    authDomain: 'nvcti-f6dfe.firebaseapp.com',
    storageBucket: 'nvcti-f6dfe.firebasestorage.app',
    measurementId: 'G-QWRQZX1DTH',
  );
}
